server:
  port: 8080
  address: 0.0.0.0
  read_timeout: 60
  write_timeout: 60
  middlewares: recovery,cors

log:
  debug: true
  level: info

mysql:
  dns: app_rw_im:im0ARqtl37J0K6H@tcp(10.40.2.7:3306)/HT_IMDB?collation=utf8mb4_unicode_ci&parseTime=true&loc=Local&timeout=10s&readTimeout=30s&writeTimeout=30s
  max_open_count: 50
  max_idle_count: 50
  tracing: false

redis:
  addr: "127.0.0.1:6379"
  passwd: "1232"
  pool_size: 100