package code

// Code generated by "codegen -type=int /Users/costalong/code/go/src/github.com/costa92/traefik-api/core/code"; DO NOT EDIT.
func init() {
	register(ErrSuccess, 200, "OK")
	register(ErrUnknown, 500, "Internal server error")
	register(ErrBind, 400, "Error occurred while binding the request body to the struct")

	register(ErrAuthParams, 200, "账号密码不能为空")
}
