server:
  name: traefik
  port: 8080
  address: 0.0.0.0
  read_timeout: 60
  write_timeout: 60
  middlewares: recovery,cors

log:
  debug: true
  level: info

mysql:
  dns: root:s0kewK7Ph#0AE9IX@tcp(127.0.0.1:3306)/blog?collation=utf8mb4_unicode_ci&parseTime=true&loc=Local&timeout=10s&readTimeout=30s&writeTimeout=30s
  max_open_count: 50
  max_idle_count: 50
  tracing: false

redis:
  addr: "127.0.0.1:6379"
  passwd: "1232"
  pool_size: 100